### ISSUE TITLE
Dynamic data not load properly with wrapper VGridVueTemplate

### ISSUE THREAD

**Issue by madesigne** [revolist/vue3-datagrid#23]
Vue3.
Here is my problem.
I have a variable initialized to null which will then be loaded with an array of 23 elements.

These elements have properties, some of which are booleans or types that must be interpreted.

But cells with for example the value false are displayed with true.

When I log what happens in an onVnodeMounted function I have the feeling that only part of the data is loaded and that the values of these data affect themselves.

`cellTemplate: VGridVueTemplate((VNode: IVNode) => h(BasicSwitch, { label: "", modelValue: VNode.model.orderPortfolioMode, // Maybe true or false but it's always true isDisabled: true, onVnodeMounted: () => { console.log(VNode); // Only 8 elements out of 23 } }))`

It would come from the VGridVueTemplate wrapper.
`cellTemplate: VGridVueTemplate((VNode: IVNode) => VNode.model.orderPortfolioMode.toString())` return always true -> KO

`cellTemplate: VGridVueTemplateConstructor((VNode: IVNode) => VNode.model.orderPortfolioMode.toString()) `return true and false -> OK

Has anyone ever had the problem?

**Comment by duese1990** [comment]
Hi madesigne,
I don't know if it's the same problem, but I have a vue component which displays an "order state". For example, my order dataset has 30 rows and only 15 rows are in the viewport when loading the grid, then I have the following issue:

With this code, only the 15 rows in the viewport are calculated correctly:
`cellTemplate: VGridVueTemplate((VNode) => h(CellOrderState, {model: VNode.model})),`

With this code all 30 rows are ok:
`cellTemplate: VGridVueTemplate(CellOrderState)`

Maybe in your case it has also to do with the viewport?

I have pushed additional data to the table data, so that I can access by model prop and go ahead with second code ... but its just a work around.

**Comment by suniga-mrs** [comment]
I can confirm that this is still an issue when rendering cell template either with JSX or Vue component.

It seems that at every 15th iteration, the rendered custom component are sharing they're own internal data. 

 [Here's a sample sandbox:](https://codesandbox.io/s/revogrid-vuecomponent-forked-648dqo?file=/src/App.vue)

If anyone can point me to the right direction on this I would be happy to work and make a PR to resolve this.

**Comment by revolist** [comment]
Should be ok in v4.
